# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[(b'dont know', b'dont know'), (b'Airbus A310', b'Airbus A310'), (b'Airbus A320', b'Airbus A320'), (b'Airbus A330', b'Airbus A330'), (b'Airbus A340', b'Airbus A340'), (b'Airbus A380', b'Airbus A380'), (b'Antonov An-148', b'Antonov An-148'), (b'AVIC ARJ-21', b'AVIC ARJ-21'), (b'Boeing 717', b'Boeing 717'), (b'Boeing 737', b'Boeing 737'), (b'Boeing 747', b'Boeing 747'), (b'Boeing 757', b'Boeing 757'), (b'Boeing 767', b'Boeing 767'), (b'Boeing 777', b'Boeing 777'), (b'Boeing 787', b'Boeing 787'), (b'Bombardier CRJ-1000', b'Bombardier CRJ-1000'), (b'Embraer 195', b'Embraer 195'), (b'Evektor EV-55', b'Evektor EV-55'), (b'Fokker 50', b'Fokker 50'), (b'Fokker 100', b'Fokker 100'), (b'Ilyushin Il-96', b'Ilyushin Il-96'), (b'Tupolev Tu-204', b'Tupolev Tu-204'), (b'Saab', b'Saab'), (b'Sukjoi Superjet-100', b'Sukjoi Superjet-100')], default='unknown', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'dont know', b'dont know'), (b'GE CFM56', b'GE CFM56'), (b'JT8D', b'JT8D'), (b'CF6', b'CF6'), (b'IAE V2500', b'IAE V2500'), (b'GE CF34', b'GE CF34'), (b'JT3D', b'JT3D'), (b'Soloviev D-30', b'Soloviev D-30'), (b'PW5000', b'PW5000'), (b'Motor Sich AI-25', b'Motor Sich AI-25'), (b'Rolls-Royce RB211', b'Rolls-Royce RB211')], default='unknown', max_length=25)),
                ('number', models.IntegerField(default=1, verbose_name='Number of engines')),
                ('positions', models.CharField(choices=[('12', 'left-right'), ('123', 'left-cen-right'), ('1234', 'left-left-right-right'), ('123456', 'left-left-cen-cen-right-right'), ('other', 'other')], max_length=60)),
                ('noise_desc', models.CharField(blank=True, max_length=500)),
                ('noise_audio', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Time of sighting')),
                ('nvp', models.IntegerField(default=1, verbose_name='Number of vapour trails')),
                ('markings', models.CharField(max_length=4096)),
                ('photos', models.CharField(max_length=4096)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Sighting.Aircraft')),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Sighting.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(choices=[('1', '10-20m'), ('2', '20-30m'), ('3', '30-40m'), ('4', '40-50m'), ('5', '50-60m'), ('6', '60-70m'), ('7', '70-80m'), ('8', '80-90m'), ('9', '90-100m'), ('10', '> 100m')], max_length=3, verbose_name='Length')),
                ('wingspan', models.CharField(choices=[('1', '10-20m'), ('2', '20-30m'), ('3', '30-40m'), ('4', '40-50m'), ('5', '50-60m'), ('6', '60-70m'), ('7', '70-80m'), ('8', '80-90m'), ('9', '90-100m'), ('10', '> 100m')], max_length=3, verbose_name='Wing Span')),
                ('tailheight', models.CharField(choices=[('1', '10-20m'), ('2', '20-30m'), ('3', '30-40m'), ('4', '40-50m'), ('5', '50-60m'), ('6', '60-70m'), ('7', '70-80m'), ('8', '80-90m'), ('9', '90-100m'), ('10', '> 100m')], max_length=3, verbose_name='Tail Height')),
            ],
        ),
        migrations.CreateModel(
            name='Spotter',
            fields=[
                ('spotter_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Wing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=2, verbose_name='Number of wings')),
                ('position', models.CharField(choices=[('A', 'Above'), ('B', 'Below'), ('M', 'Fixed at mid-point')], max_length=3, verbose_name='Fuselage position')),
                ('swept', models.IntegerField(default=10, verbose_name='Swept Rearwards (degrees)')),
            ],
        ),
        migrations.AddField(
            model_name='sighting',
            name='spotter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Sighting.Spotter'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='engine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Sighting.Engine'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Sighting.Size'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='wing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Sighting.Wing'),
        ),
    ]
